### PR TITLE
#190: If the transaction fails, the preview is left in an invalid state

### LINKED ISSUE #190: If the transaction fails, the preview is left in an invalid state
On the transaction preview page, if the "Send" button is pressed and the operation fails, the "Back" button remains deactivated and the amount of coins in the outputs is left multiplied by 1000000. The "Back" button must be reactivated and the amount of coins shown must not be modified.

### PR DESCRIPTION
**Pull request by AndreiIarovoi**
Fixes #190 

Changes:
- setEnabled() method has been added to the ButtonComponent
- OnDestroy hook has been implemented by the SendVerifyComponent component to disable toaster notifications

Comment: The problem with multiplied coins value will be fixed in scope of the issue #188

### CODE REVIEW

File: src/app/components/pages/send-skycoin/send-verify/send-verify.component.ts [hunk 1]
```diff
@@ -47,9 +52,11 @@ export class SendVerifyComponent {
   }
 
   private onError(error) {
+    const errorMessage = parseResponseMessage(error['_body']);
```
Comment (Senyoret1) [inline src/app/components/pages/send-skycoin/send-verify/send-verify.component.ts]: `error['_body']` is undefined, so an error occurs when reaching this line.

To test the errors, please modify the last line of `WalletService.injectTransaction` with `return Observable.throw(new Error("Error"));`

Comment (AndreiIarovoi) [reply src/app/components/pages/send-skycoin/send-verify/send-verify.component.ts]: Fixed
